theme: jekyll-theme-cayman
logo: https://drive.google.com/open?id=0BxBf-ekgpA4gcUoyazZob3oyZzA
title: Welcome to MoveMate Page
description: An aid for universitary students to share their trips to/from university with their mates
motto: For students. By students.
