theme: jekyll-theme-cayman
logo: http://zdnet3.cbsistatic.com/hub/i/2015/09/01/cb834e24-18e7-4f0a-a9bf-4c2917187d3f/83bb139aac01023dbf3e55a3d1789ad8/google-new-logo.png
title: Welcome to MoveMate Page
description: An aid for universitary students to share their travels to/from university with their mates

//https://github.com/movers-gcw/MoveMate/blob/master/logo.png
