theme: jekyll-theme-cayman
logo: https://github.com/movers-gcw/MoveMate/blob/master/logo.png
title: Welcome to MoveMate Page
description: An aid for universitary students to share their travels to/from university with their mates
